#!/bin/bash
echo Running clean
make clean
./cleanup.sh >/dev/null
echo Committing the rest
svn add * */* */*/* */*/*/* */*/*/*/*
svn commit --message x
svn update
# svn revert * */* */*/* */*/*/* */*/*/*/*
exit 0

